const languages = new Map([
  ["English", "en"],
  ["Spanish", "es"],
  ["French", "fr"],
  ["German", "de"],
  ["Italian", "it"],
  ["Chinese", "zh"],
  ["Japanese", "ja"],
  ["Russian", "ru"],
  ["Arabic", "ar"],
  ["Portuguese", "pt"],
  ["Dutch", "nl"],
  ["Korean", "ko"],
  ["Swedish", "sv"],
  ["Norwegian", "no"],
  ["Danish", "da"],
  ["Finnish", "fi"],
  ["Ukrainian", "uk"],
  ["Polish", "pl"],
  ["Czech", "cs"],
  ["Hungarian", "hu"],
  ["Turkish", "tr"],
  ["Thai", "th"],
  ["Vietnamese", "vi"],
  ["Indonesian", "id"],
  ["Malay", "ms"],
  ["Filipino", "fil"],
  ["Romanian", "ro"],
  ["Bulgarian", "bg"],
  ["Croatian", "hr"],
  ["Slovak", "sk"],
  ["Slovenian", "sl"],
  ["Estonian", "et"],
  ["Latvian", "lv"],
  ["Lithuanian", "lt"],
  ["Icelandic", "is"],
  ["Irish", "ga"],
  ["Welsh", "cy"],
  ["Serbian", "sr"],
  ["Bosnian", "bs"],
  ["Macedonian", "mk"],
  ["Albanian", "sq"],
  ["Belarusian", "be"],
  ["Kazakh", "kk"],
  ["Uzbek", "uz"],
  ["Azerbaijani", "az"],
  ["Georgian", "ka"],
  ["Armenian", "hy"],
  ["Mongolian", "mn"],
  ["Farsi", "fa"],
  ["Hebrew", "he"],
  ["Hindi", "hi"],
  ["Bengali", "bn"],
  ["Tamil", "ta"],
  ["Telugu", "te"],
  ["Marathi", "mr"],
  ["Gujarati", "gu"],
  ["Punjabi", "pa"],
  ["Urdu", "ur"],
]);

const REQUESTS = {
  PREFERRED_LANGUAGES_REQUEST: "preferredLanguagesRequest",
  PING: "ping",
};
const RESPONSES = {
  PREFERRED_LANGUAGES_DATA: "preferredLanguagesData",
  PONG: "pong",
};
